provider: kafka
major-version: 3
docker: true
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter

worktreeAllowedChanges: |-
  sdk/**/pulumi-plugin.json
  sdk/dotnet/Pulumi.*.csproj
  sdk/go/*/internal/pulumiUtilities.go
  sdk/nodejs/package.json
  sdk/python/pyproject.toml

publish:
  goSdk:
    usePush: true
