// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kafka.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetTopicsList {
    /**
     * @return A map of string k/v attributes.
     * 
     */
    private Map<String,String> config;
    /**
     * @return Number of partitions.
     * 
     */
    private Integer partitions;
    /**
     * @return Number of replicas.
     * 
     */
    private Integer replicationFactor;
    /**
     * @return The name of the topic.
     * 
     */
    private String topicName;

    private GetTopicsList() {}
    /**
     * @return A map of string k/v attributes.
     * 
     */
    public Map<String,String> config() {
        return this.config;
    }
    /**
     * @return Number of partitions.
     * 
     */
    public Integer partitions() {
        return this.partitions;
    }
    /**
     * @return Number of replicas.
     * 
     */
    public Integer replicationFactor() {
        return this.replicationFactor;
    }
    /**
     * @return The name of the topic.
     * 
     */
    public String topicName() {
        return this.topicName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTopicsList defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Map<String,String> config;
        private Integer partitions;
        private Integer replicationFactor;
        private String topicName;
        public Builder() {}
        public Builder(GetTopicsList defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.config = defaults.config;
    	      this.partitions = defaults.partitions;
    	      this.replicationFactor = defaults.replicationFactor;
    	      this.topicName = defaults.topicName;
        }

        @CustomType.Setter
        public Builder config(Map<String,String> config) {
            if (config == null) {
              throw new MissingRequiredPropertyException("GetTopicsList", "config");
            }
            this.config = config;
            return this;
        }
        @CustomType.Setter
        public Builder partitions(Integer partitions) {
            if (partitions == null) {
              throw new MissingRequiredPropertyException("GetTopicsList", "partitions");
            }
            this.partitions = partitions;
            return this;
        }
        @CustomType.Setter
        public Builder replicationFactor(Integer replicationFactor) {
            if (replicationFactor == null) {
              throw new MissingRequiredPropertyException("GetTopicsList", "replicationFactor");
            }
            this.replicationFactor = replicationFactor;
            return this;
        }
        @CustomType.Setter
        public Builder topicName(String topicName) {
            if (topicName == null) {
              throw new MissingRequiredPropertyException("GetTopicsList", "topicName");
            }
            this.topicName = topicName;
            return this;
        }
        public GetTopicsList build() {
            final var _resultValue = new GetTopicsList();
            _resultValue.config = config;
            _resultValue.partitions = partitions;
            _resultValue.replicationFactor = replicationFactor;
            _resultValue.topicName = topicName;
            return _resultValue;
        }
    }
}
