// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kafka;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AclArgs extends com.pulumi.resources.ResourceArgs {

    public static final AclArgs Empty = new AclArgs();

    @Import(name="aclHost", required=true)
    private Output<String> aclHost;

    public Output<String> aclHost() {
        return this.aclHost;
    }

    @Import(name="aclOperation", required=true)
    private Output<String> aclOperation;

    public Output<String> aclOperation() {
        return this.aclOperation;
    }

    @Import(name="aclPermissionType", required=true)
    private Output<String> aclPermissionType;

    public Output<String> aclPermissionType() {
        return this.aclPermissionType;
    }

    @Import(name="aclPrincipal", required=true)
    private Output<String> aclPrincipal;

    public Output<String> aclPrincipal() {
        return this.aclPrincipal;
    }

    /**
     * The name of the resource
     * 
     */
    @Import(name="aclResourceName", required=true)
    private Output<String> aclResourceName;

    /**
     * @return The name of the resource
     * 
     */
    public Output<String> aclResourceName() {
        return this.aclResourceName;
    }

    @Import(name="aclResourceType", required=true)
    private Output<String> aclResourceType;

    public Output<String> aclResourceType() {
        return this.aclResourceType;
    }

    @Import(name="resourcePatternTypeFilter")
    private @Nullable Output<String> resourcePatternTypeFilter;

    public Optional<Output<String>> resourcePatternTypeFilter() {
        return Optional.ofNullable(this.resourcePatternTypeFilter);
    }

    private AclArgs() {}

    private AclArgs(AclArgs $) {
        this.aclHost = $.aclHost;
        this.aclOperation = $.aclOperation;
        this.aclPermissionType = $.aclPermissionType;
        this.aclPrincipal = $.aclPrincipal;
        this.aclResourceName = $.aclResourceName;
        this.aclResourceType = $.aclResourceType;
        this.resourcePatternTypeFilter = $.resourcePatternTypeFilter;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AclArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AclArgs $;

        public Builder() {
            $ = new AclArgs();
        }

        public Builder(AclArgs defaults) {
            $ = new AclArgs(Objects.requireNonNull(defaults));
        }

        public Builder aclHost(Output<String> aclHost) {
            $.aclHost = aclHost;
            return this;
        }

        public Builder aclHost(String aclHost) {
            return aclHost(Output.of(aclHost));
        }

        public Builder aclOperation(Output<String> aclOperation) {
            $.aclOperation = aclOperation;
            return this;
        }

        public Builder aclOperation(String aclOperation) {
            return aclOperation(Output.of(aclOperation));
        }

        public Builder aclPermissionType(Output<String> aclPermissionType) {
            $.aclPermissionType = aclPermissionType;
            return this;
        }

        public Builder aclPermissionType(String aclPermissionType) {
            return aclPermissionType(Output.of(aclPermissionType));
        }

        public Builder aclPrincipal(Output<String> aclPrincipal) {
            $.aclPrincipal = aclPrincipal;
            return this;
        }

        public Builder aclPrincipal(String aclPrincipal) {
            return aclPrincipal(Output.of(aclPrincipal));
        }

        /**
         * @param aclResourceName The name of the resource
         * 
         * @return builder
         * 
         */
        public Builder aclResourceName(Output<String> aclResourceName) {
            $.aclResourceName = aclResourceName;
            return this;
        }

        /**
         * @param aclResourceName The name of the resource
         * 
         * @return builder
         * 
         */
        public Builder aclResourceName(String aclResourceName) {
            return aclResourceName(Output.of(aclResourceName));
        }

        public Builder aclResourceType(Output<String> aclResourceType) {
            $.aclResourceType = aclResourceType;
            return this;
        }

        public Builder aclResourceType(String aclResourceType) {
            return aclResourceType(Output.of(aclResourceType));
        }

        public Builder resourcePatternTypeFilter(@Nullable Output<String> resourcePatternTypeFilter) {
            $.resourcePatternTypeFilter = resourcePatternTypeFilter;
            return this;
        }

        public Builder resourcePatternTypeFilter(String resourcePatternTypeFilter) {
            return resourcePatternTypeFilter(Output.of(resourcePatternTypeFilter));
        }

        public AclArgs build() {
            $.aclHost = Objects.requireNonNull($.aclHost, "expected parameter 'aclHost' to be non-null");
            $.aclOperation = Objects.requireNonNull($.aclOperation, "expected parameter 'aclOperation' to be non-null");
            $.aclPermissionType = Objects.requireNonNull($.aclPermissionType, "expected parameter 'aclPermissionType' to be non-null");
            $.aclPrincipal = Objects.requireNonNull($.aclPrincipal, "expected parameter 'aclPrincipal' to be non-null");
            $.aclResourceName = Objects.requireNonNull($.aclResourceName, "expected parameter 'aclResourceName' to be non-null");
            $.aclResourceType = Objects.requireNonNull($.aclResourceType, "expected parameter 'aclResourceType' to be non-null");
            return $;
        }
    }

}
