// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kafka;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.kafka.Utilities;
import com.pulumi.kafka.inputs.GetTopicArgs;
import com.pulumi.kafka.inputs.GetTopicPlainArgs;
import com.pulumi.kafka.outputs.GetTopicResult;
import com.pulumi.kafka.outputs.GetTopicsResult;
import com.pulumi.resources.InvokeArgs;
import java.util.concurrent.CompletableFuture;

public final class KafkaFunctions {
    public static Output<GetTopicResult> getTopic(GetTopicArgs args) {
        return getTopic(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetTopicResult> getTopicPlain(GetTopicPlainArgs args) {
        return getTopicPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetTopicResult> getTopic(GetTopicArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("kafka:index:getTopic", TypeShape.of(GetTopicResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetTopicResult> getTopic(GetTopicArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("kafka:index:getTopic", TypeShape.of(GetTopicResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetTopicResult> getTopicPlain(GetTopicPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("kafka:index:getTopic", TypeShape.of(GetTopicResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetTopicsResult> getTopics() {
        return getTopics(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetTopicsResult> getTopicsPlain() {
        return getTopicsPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<GetTopicsResult> getTopics(InvokeArgs args) {
        return getTopics(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetTopicsResult> getTopicsPlain(InvokeArgs args) {
        return getTopicsPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetTopicsResult> getTopics(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("kafka:index:getTopics", TypeShape.of(GetTopicsResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetTopicsResult> getTopics(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("kafka:index:getTopics", TypeShape.of(GetTopicsResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetTopicsResult> getTopicsPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("kafka:index:getTopics", TypeShape.of(GetTopicsResult.class), args, Utilities.withVersion(options));
    }
}
