// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The `kafka.Topic` resource manages Apache Kafka topics, including their partition count, replication factor, and various configuration parameters. This resource supports non-destructive partition count increases.
 *
 * ## Example Usage
 *
 * ### Basic Topic
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as kafka from "@pulumi/kafka";
 *
 * const example = new kafka.Topic("example", {
 *     name: "example-topic",
 *     replicationFactor: 3,
 *     partitions: 10,
 * });
 * ```
 *
 * ### Topic with Common Configurations
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as kafka from "@pulumi/kafka";
 *
 * const logs = new kafka.Topic("logs", {
 *     name: "application-logs",
 *     replicationFactor: 3,
 *     partitions: 50,
 *     config: {
 *         "retention.ms": "604800000",
 *         "segment.ms": "86400000",
 *         "cleanup.policy": "delete",
 *         "compression.type": "gzip",
 *     },
 * });
 * ```
 *
 * ### Compacted Topic for Event Sourcing
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as kafka from "@pulumi/kafka";
 *
 * const events = new kafka.Topic("events", {
 *     name: "user-events",
 *     replicationFactor: 3,
 *     partitions: 100,
 *     config: {
 *         "cleanup.policy": "compact",
 *         "retention.ms": "-1",
 *         "min.compaction.lag.ms": "3600000",
 *         "delete.retention.ms": "86400000",
 *         "compression.type": "lz4",
 *         "segment.bytes": "1073741824",
 *     },
 * });
 * ```
 *
 * ### High-Throughput Topic
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as kafka from "@pulumi/kafka";
 *
 * const metrics = new kafka.Topic("metrics", {
 *     name: "system-metrics",
 *     replicationFactor: 2,
 *     partitions: 200,
 *     config: {
 *         "retention.ms": "86400000",
 *         "segment.ms": "3600000",
 *         "compression.type": "lz4",
 *         "max.message.bytes": "1048576",
 *         "min.insync.replicas": "2",
 *         "unclean.leader.election.enable": "false",
 *     },
 * });
 * ```
 *
 * ## Configuration Parameters
 *
 * The `config` map supports all Kafka topic-level configurations. Common configurations include:
 *
 * ### Retention Settings
 * - `retention.ms` - How long to retain messages (in milliseconds). Default: 604800000 (7 days)
 * - `retention.bytes` - Maximum size of the log before deleting old segments. Default: -1 (no limit)
 * - `segment.ms` - Time after which a log segment should be rotated. Default: 604800000 (7 days)
 * - `segment.bytes` - Maximum size of a single log segment file. Default: 1073741824 (1GB)
 *
 * ### Cleanup and Compaction
 * - `cleanup.policy` - Either "delete" or "compact" or both "compact,delete". Default: "delete"
 * - `min.compaction.lag.ms` - Minimum time a message will remain uncompacted. Default: 0
 * - `delete.retention.ms` - How long to retain delete tombstone markers for compacted topics. Default: 86400000 (1 day)
 *
 * ### Compression
 * - `compression.type` - Compression codec: "uncompressed", "zstd", "lz4", "snappy", "gzip", "producer". Default: "producer"
 *
 * ### Replication and Durability
 * - `min.insync.replicas` - Minimum number of replicas that must acknowledge a write. Default: 1
 * - `unclean.leader.election.enable` - Whether to allow replicas not in ISR to be elected leader. Default: false
 *
 * ### Message Size
 * - `max.message.bytes` - Maximum size of a message. Default: 1048588 (~1MB)
 * - `message.timestamp.type` - Whether to use CreateTime or LogAppendTime. Default: "CreateTime"
 *
 * For a complete list of configurations, refer to the [Kafka documentation](https://kafka.apache.org/documentation/#topicconfigs).
 *
 * > **Note:** Increasing the partition count is supported without recreating the topic. However, decreasing partitions requires topic recreation.
 *
 * ## Import
 *
 * Existing Kafka topics can be imported using the topic name:
 *
 * ```sh
 * $ pulumi import kafka:index/topic:Topic example example-topic
 * ```
 */
export class Topic extends pulumi.CustomResource {
    /**
     * Get an existing Topic resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TopicState, opts?: pulumi.CustomResourceOptions): Topic {
        return new Topic(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kafka:index/topic:Topic';

    /**
     * Returns true if the given object is an instance of Topic.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Topic {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Topic.__pulumiType;
    }

    /**
     * A map of string k/v attributes.
     */
    public readonly config!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The name of the topic.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Number of partitions.
     */
    public readonly partitions!: pulumi.Output<number>;
    /**
     * Number of replicas.
     */
    public readonly replicationFactor!: pulumi.Output<number>;

    /**
     * Create a Topic resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TopicArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TopicArgs | TopicState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TopicState | undefined;
            resourceInputs["config"] = state ? state.config : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["partitions"] = state ? state.partitions : undefined;
            resourceInputs["replicationFactor"] = state ? state.replicationFactor : undefined;
        } else {
            const args = argsOrState as TopicArgs | undefined;
            if ((!args || args.partitions === undefined) && !opts.urn) {
                throw new Error("Missing required property 'partitions'");
            }
            if ((!args || args.replicationFactor === undefined) && !opts.urn) {
                throw new Error("Missing required property 'replicationFactor'");
            }
            resourceInputs["config"] = args ? args.config : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["partitions"] = args ? args.partitions : undefined;
            resourceInputs["replicationFactor"] = args ? args.replicationFactor : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Topic.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Topic resources.
 */
export interface TopicState {
    /**
     * A map of string k/v attributes.
     */
    config?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the topic.
     */
    name?: pulumi.Input<string>;
    /**
     * Number of partitions.
     */
    partitions?: pulumi.Input<number>;
    /**
     * Number of replicas.
     */
    replicationFactor?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Topic resource.
 */
export interface TopicArgs {
    /**
     * A map of string k/v attributes.
     */
    config?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the topic.
     */
    name?: pulumi.Input<string>;
    /**
     * Number of partitions.
     */
    partitions: pulumi.Input<number>;
    /**
     * Number of replicas.
     */
    replicationFactor: pulumi.Input<number>;
}
